[book]
authors = ["yukinotech"]
language = "cn"
multilingual = false
src = "src"
title = "typescript迷你书"

[build]
build-dir = "docs"

[output.html]
git-repository-url = "https://github.com/yukinotech/typescript-mini-book"
default-theme = "rust"
preferred-dark-theme = "navy"